// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Expenses.Persistence;

#nullable disable

namespace POS.Expenses.Persistence.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260722130124_InitialExpenses")]
    partial class InitialExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("expenses")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Expenses.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("LinkedGoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "POS.Expenses.Domain.Expense.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TaxAmount", "POS.Expenses.Domain.Expense.TaxAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TaxCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("LinkedGoodsReceiptId")
                        .HasDatabaseName("IX_Expenses_Capitalised")
                        .HasFilter("[LinkedGoodsReceiptId] IS NOT NULL");

                    b.HasIndex("TenantId", "ExpenseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Expenses_Number");

                    b.HasIndex("TenantId", "Status", "IncurredOn")
                        .HasDatabaseName("IX_Expenses_Approval");

                    b.HasIndex("TenantId", "CompanyId", "BranchId", "Category", "IncurredOn")
                        .HasDatabaseName("IX_Expenses_Reporting");

                    b.ToTable("Expenses", "expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
