<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\POS.Common\POS.Common.csproj" />
    <ProjectReference Include="..\..\..\Shared\POS.Contracts\POS.Contracts.csproj" />
    <ProjectReference Include="..\POS.Inventory.Domain\POS.Inventory.Domain.csproj" />
  </ItemGroup>

</Project>
