// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Sales.Persistence;

#nullable disable

namespace POS.Sales.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Sales.Domain.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "POS.Sales.Domain.CashMovement.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("CashMovements", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.PriceAdjustment", b =>
                {
                    b.Property<Guid>("SaleLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("AuthorisedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "POS.Sales.Domain.PriceAdjustment.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.HasKey("SaleLineId", "Sequence");

                    b.HasIndex("AuthorisedBy")
                        .HasDatabaseName("IX_SaleLineAdjustments_AuthorisedBy");

                    b.ToTable("SaleLineAdjustments", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwningTerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("AmountTendered", "POS.Sales.Domain.Sale.AmountTendered#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("AmountTenderedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("AmountTenderedCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ChangeGiven", "POS.Sales.Domain.Sale.ChangeGiven#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("ChangeGivenAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("ChangeGivenCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ReceiptNumber", "POS.Sales.Domain.Sale.ReceiptNumber#ReceiptNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Sequence")
                                .HasColumnType("bigint")
                                .HasColumnName("ReceiptSequence");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ReceiptSeries");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RoundingAdjustment", "POS.Sales.Domain.Sale.RoundingAdjustment#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("RoundingAdjustmentAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("RoundingAdjustmentCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalDiscount", "POS.Sales.Domain.Sale.TotalDiscount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalDiscountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TotalDiscountCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalExclusiveTax", "POS.Sales.Domain.Sale.TotalExclusiveTax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalExclusiveTaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TotalExclusiveTaxCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalInclusiveTax", "POS.Sales.Domain.Sale.TotalInclusiveTax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalInclusiveTaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TotalInclusiveTaxCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalTax", "POS.Sales.Domain.Sale.TotalTax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalTaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TotalTaxCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ShiftId")
                        .HasDatabaseName("IX_Sales_Shift");

                    b.HasIndex("TenantId", "BranchId", "BusinessDate")
                        .HasDatabaseName("IX_Sales_BusinessDate");

                    b.HasIndex("TenantId", "TerminalId", "Status")
                        .HasDatabaseName("IX_Sales_Status");

                    b.ToTable("Sales", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PriceListVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TaxInclusivePricing")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("DiscountAmount", "POS.Sales.Domain.SaleLine.DiscountAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("DiscountCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("GrossAmount", "POS.Sales.Domain.SaleLine.GrossAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("GrossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("GrossCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NetAmount", "POS.Sales.Domain.SaleLine.NetAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("NetAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("NetCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TaxAmount", "POS.Sales.Domain.SaleLine.TaxAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("TaxCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitCostAtSale", "POS.Sales.Domain.SaleLine.UnitCostAtSale#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UnitCostAtSaleAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("UnitCostAtSaleCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrice", "POS.Sales.Domain.SaleLine.UnitPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("UnitPriceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("IX_SaleLines_Variant");

                    b.ToTable("SaleLines", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("CountedCash", "POS.Sales.Domain.Shift.CountedCash#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("CountedCashAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("CountedCashCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ExpectedCash", "POS.Sales.Domain.Shift.ExpectedCash#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("ExpectedCashAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("ExpectedCashCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OpeningFloat", "POS.Sales.Domain.Shift.OpeningFloat#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("OpeningFloatAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("OpeningFloatCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Variance", "POS.Sales.Domain.Shift.Variance#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("VarianceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("VarianceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TerminalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Shifts_OpenPerTerminal")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("TenantId", "BranchId", "BusinessDate")
                        .HasDatabaseName("IX_Shifts_BusinessDate");

                    b.ToTable("Shifts", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "POS.Sales.Domain.Tender.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_Tenders_Payment");

                    b.HasIndex("SaleId");

                    b.ToTable("Tenders", "sales");
                });

            modelBuilder.Entity("POS.Sales.Domain.CashMovement", b =>
                {
                    b.HasOne("POS.Sales.Domain.Shift", null)
                        .WithMany("CashMovements")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POS.Sales.Domain.PriceAdjustment", b =>
                {
                    b.HasOne("POS.Sales.Domain.SaleLine", null)
                        .WithMany("Adjustments")
                        .HasForeignKey("SaleLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Sales.Domain.Sale", b =>
                {
                    b.OwnsOne("POS.Sales.Domain.SaleReference", "Reverses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("BusinessDate")
                                .HasColumnType("date")
                                .HasColumnName("ReversesBusinessDate");

                            b1.Property<string>("ReceiptNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ReversesReceiptNumber");

                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ReversesSaleId");

                            b1.HasKey("Id");

                            b1.ToTable("Sales", "sales");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Reverses");
                });

            modelBuilder.Entity("POS.Sales.Domain.SaleLine", b =>
                {
                    b.HasOne("POS.Sales.Domain.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POS.Sales.Domain.Tender", b =>
                {
                    b.HasOne("POS.Sales.Domain.Sale", null)
                        .WithMany("Tenders")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POS.Sales.Domain.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("POS.Sales.Domain.SaleLine", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("POS.Sales.Domain.Shift", b =>
                {
                    b.Navigation("CashMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
