// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Inventory.Persistence;

#nullable disable

namespace POS.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260722113816_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Inventory.Domain.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastMovementAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("AverageUnitCost", "POS.Inventory.Domain.StockBalance.AverageUnitCost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("decimal(19,6)")
                                .HasColumnName("AverageUnitCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AverageUnitCostCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalValue", "POS.Inventory.Domain.StockBalance.TotalValue#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("decimal(19,6)")
                                .HasColumnName("TotalValueAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TotalValueCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WarehouseId")
                        .HasDatabaseName("IX_StockBalances_Negative")
                        .HasFilter("[QuantityOnHand] < 0");

                    b.HasIndex("TenantId", "WarehouseId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockBalances_Warehouse_Variant");

                    b.ToTable("StockBalances", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Reference", "POS.Inventory.Domain.StockMovement.Reference#StockDocumentReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("DocumentId");

                            b1.Property<string>("DocumentNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DocumentNumber");

                            b1.Property<int>("DocumentType")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalCost", "POS.Inventory.Domain.StockMovement.TotalCost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("decimal(19,6)")
                                .HasColumnName("TotalCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TotalCostCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitCost", "POS.Inventory.Domain.StockMovement.UnitCost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("decimal(19,6)")
                                .HasColumnName("UnitCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitCostCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BusinessDate")
                        .HasDatabaseName("IX_StockMovements_BusinessDate");

                    b.HasIndex("TenantId", "WarehouseId", "VariantId", "OccurredAt")
                        .HasDatabaseName("IX_StockMovements_Balance");

                    b.ToTable("StockMovements", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DispatchedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InTransitWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VarianceWriteOffReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("VarianceWrittenOffAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VarianceWrittenOffByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TransferNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_StockTransfers_Number");

                    b.HasIndex("TenantId", "Status", "DispatchedAt")
                        .HasDatabaseName("IX_StockTransfers_Status");

                    b.ToTable("StockTransfers", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.StockTransferLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("QuantityReceived")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantitySent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockTransferId");

                    b.ToTable("StockTransferLines", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsBlind")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("StartedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StocktakeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StocktakeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Stocktakes_Number");

                    b.HasIndex("TenantId", "WarehouseId", "Status")
                        .HasDatabaseName("IX_Stocktakes_Warehouse_Status");

                    b.ToTable("Stocktakes", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.StocktakeLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CountedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CountedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CountedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecountCount")
                        .HasColumnType("int");

                    b.Property<Guid>("StocktakeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StocktakeId");

                    b.ToTable("StocktakeLines", "inventory");
                });

            modelBuilder.Entity("POS.Inventory.Domain.StockTransferLine", b =>
                {
                    b.HasOne("POS.Inventory.Domain.StockTransfer", null)
                        .WithMany("Lines")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Inventory.Domain.StocktakeLine", b =>
                {
                    b.HasOne("POS.Inventory.Domain.Stocktake", null)
                        .WithMany("Lines")
                        .HasForeignKey("StocktakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POS.Inventory.Domain.StockTransfer", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("POS.Inventory.Domain.Stocktake", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
