// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Fiscal.Persistence;

#nullable disable

namespace POS.Fiscal.Persistence.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    partial class FiscalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fiscal")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Fiscal.Domain.FiscalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorityIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FormattedNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IssuedOffline")
                        .HasColumnType("bit");

                    b.Property<string>("PreviousDocumentHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SignatureAlgorithm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SignatureValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersededByDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("TransmissionDueBy")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TransmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Status", "TransmissionDueBy")
                        .HasDatabaseName("IX_FiscalDocuments_Transmission");

                    b.HasIndex("TenantId", "SaleId")
                        .HasDatabaseName("IX_FiscalDocuments_Sale");

                    b.HasIndex("CompanyId", "TerminalId", "Series", "IssuedAt")
                        .HasDatabaseName("IX_FiscalDocuments_Chain");

                    b.HasIndex("CompanyId", "TerminalId", "Series", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_FiscalDocuments_Number");

                    b.ToTable("FiscalDocuments", "fiscal");
                });

            modelBuilder.Entity("POS.Fiscal.Persistence.FiscalSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastAllocated")
                        .HasColumnType("bigint");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "TerminalId", "Series")
                        .IsUnique()
                        .HasDatabaseName("UX_FiscalSequences_Series");

                    b.ToTable("FiscalSequences", "fiscal");
                });

            modelBuilder.Entity("POS.Fiscal.Domain.FiscalDocument", b =>
                {
                    b.OwnsMany("POS.Fiscal.Domain.FiscalTransmissionAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AttemptNumber")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("AttemptedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("AuthorityIdentifier")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("FiscalDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsRetryable")
                                .HasColumnType("bit");

                            b1.Property<string>("MessageCode")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("MessageText")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("FiscalDocumentId");

                            b1.ToTable("FiscalTransmissionAttempts", "fiscal");

                            b1.WithOwner()
                                .HasForeignKey("FiscalDocumentId");
                        });

                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
